before_script: 
  - cd server
  - npm install mocha
  - npm install chai
  - npm install codeclimate-test-reporter nyc -g
language: node_js
node_js:
  - "stable" 
addons:
  code_climate:
    repo_token: 3c06e6c896483b1436d39a14d793dc8c3acea0672a6b2ace35545a8e3bc1324c

script:
  - nyc npm test
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info